name: Test
on:
  push:
    branches:
      - main
  pull_request:
# TODO: replace `<linter-name>` with yours
jobs:
  test-check:
    name: runner / <linter-name> (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          locale: "US"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          locale: "US"
          workdir: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / <linter-name> (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          filter_mode: file
          fail_level: any
      - name: check the exit code
        if: ${{ !success() }}
        run: echo 'The previous step should fail' && exit 1

  test-sarif:
    name: runner / <linter-name> (sarif)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          reporter: sarif
          locale: "US"
